---
- name: Get device information
  hosts: Lab_nm2
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Get software and uptime information
      juniper_junos_command:        
        commands: 
          - "show version"        
          - "show system uptime"
      register: junos_result

    - name: Print response
      debug:
        var: junos_result
