---
- name: Get device information
  hosts: JUNOS
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Get software and uptime information
      juniper_junos_command:        
        host: "{{ junos_host }}"
        user: "{{ ADMUSER }}"
        passwd: "{{ ADMPASS }}"
        commands: 
          - "show version"   
      register: junos_result

    - name: Print response
      debug:
        var: junos_result
